id: Cyberint-Testplaybook
version: 8
vcShouldKeepItemLegacyProdMachine: false
name: Cyberint-Testplaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 00b5df7f-2dc1-47cb-8cab-df18177daf68
    type: start
    task:
      id: 00b5df7f-2dc1-47cb-8cab-df18177daf68
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: ed3740f0-63b9-4f15-8778-d79429e164b8
    type: regular
    task:
      id: ed3740f0-63b9-4f15-8778-d79429e164b8
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 07f14a02-0ba2-4d66-8b07-e13c0a9998ad
    type: regular
    task:
      id: 07f14a02-0ba2-4d66-8b07-e13c0a9998ad
      version: -1
      name: cyberint-alerts-fetch
      script: '|||cyberint-alerts-fetch'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 7c376c5a-d64c-4abb-8faf-ba26f6cbe732
    type: condition
    task:
      id: 7c376c5a-d64c-4abb-8faf-ba26f6cbe732
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.confidence
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.status
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.created_by.email
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.created_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.category
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.title
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.ref_id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 544b5577-7223-4fab-81aa-c3b993cc8726
    type: regular
    task:
      id: 544b5577-7223-4fab-81aa-c3b993cc8726
      version: -1
      name: cyberint-alerts-status-update
      script: '|||cyberint-alerts-status-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      alert_ref_ids:
        simple: ADS10-3
      closure_reason: {}
      status:
        simple: acknowledged
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a35a76ac-7aa7-4497-8711-0415f44d14ed
    type: condition
    task:
      id: a35a76ac-7aa7-4497-8711-0415f44d14ed
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.ref_id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Cyberint.Alert.status
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: Cyberint.Alert.status
            iscontext: true
          right:
            value:
              simple: acknowledged
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 7df0d897-9f77-4708-898e-7dc1c82cd103
    type: regular
    task:
      id: 7df0d897-9f77-4708-898e-7dc1c82cd103
      version: -1
      name: cyberint-alerts-get-attachment
      script: '|||cyberint-alerts-get-attachment'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      alert_ref_id:
        simple: ARG-4
      attachment_id:
        simple: "166"
      attachment_name:
        simple: Argos Screenshot of the Phishing Website.png
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: ef6d73ce-83bd-42d8-83ac-8b1e1228c948
    type: regular
    task:
      id: ef6d73ce-83bd-42d8-83ac-8b1e1228c948
      version: -1
      name: cyberint-alerts-analysis-report
      script: '|||cyberint-alerts-analysis-report'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      alert_ref_id:
        simple: ARG-4
      report_name:
        simple: Expert Analysis - Active Phishing Website Targeting Company.pdf
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: e0d775bd-8950-41a8-8018-fb48883c7529
    type: title
    task:
      id: e0d775bd-8950-41a8-8018-fb48883c7529
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1615,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
